import { Alumni, FacultyMember } from "./interfaces";

export const alumniList: Alumni[] = [
    {
        name: "Alice Johnson",
        email: "alice15@university.edu",
        currentJob: "Process Engineer at ABC Corp",
        hometown: "Dhaka",
        phone: "+880123456789",
        photo: "https://i.pravatar.cc/150?img=1",
        series: 15,
    },
    {
        name: "Bob Smith",
        email: "bob15@university.edu",
        currentJob: "Research Scientist at XYZ Labs",
        hometown: "Chittagong",
        phone: "+880987654321",
        photo: "https://i.pravatar.cc/150?img=2",
        series: 15,
    },
    {
        name: "Catherine Lee",
        email: "catherine15@university.edu",
        currentJob: "Chemical Analyst at DEF Inc",
        hometown: "Khulna",
        phone: "+8801122334455",
        photo: "https://i.pravatar.cc/150?img=3",
        series: 15,
    },
    {
        name: "David Kim",
        email: "david15@university.edu",
        currentJob: "Project Engineer at GHI Ltd",
        hometown: "Rajshahi",
        phone: "+8802233445566",
        photo: "https://i.pravatar.cc/150?img=4",
        series: 15,
    },
    {
        name: "Emily Davis",
        email: "emily15@university.edu",
        currentJob: "Production Manager at JKL Corp",
        hometown: "Sylhet",
        phone: "+8803344556677",
        photo: "https://i.pravatar.cc/150?img=5",
        series: 15,
    },
    {
        name: "Frank Brown",
        email: "frank15@university.edu",
        currentJob: "Quality Control Engineer at MNO Ltd",
        hometown: "Barisal",
        phone: "+8804455667788",
        photo: "https://i.pravatar.cc/150?img=6",
        series: 15,
    },
    {
        name: "George White",
        email: "george15@university.edu",
        currentJob: "Research Associate at PQR Labs",
        hometown: "Mymensingh",
        phone: "+8805566778899",
        photo: "https://i.pravatar.cc/150?img=7",
        series: 15,
    },
    {
        name: "Hannah Green",
        email: "hannah15@university.edu",
        currentJob: "Process Engineer at STU Corp",
        hometown: "Tangail",
        phone: "+8806677889900",
        photo: "https://i.pravatar.cc/150?img=8",
        series: 15,
    },
    {
        name: "Ian Black",
        email: "ian15@university.edu",
        currentJob: "Assistant Engineer at VWX Ltd",
        hometown: "Jessore",
        phone: "+8807788990011",
        photo: "https://i.pravatar.cc/150?img=9",
        series: 15,
    },
    {
        name: "Julia Brown",
        email: "julia15@university.edu",
        currentJob: "Lab Technician at YZA Labs",
        hometown: "Comilla",
        phone: "+8808899001122",
        photo: "https://i.pravatar.cc/150?img=10",
        series: 15,
    },
    {
        name: "Kevin Lee",
        email: "kevin15@university.edu",
        currentJob: "Engineer at LMN Ltd",
        hometown: "Dhaka",
        phone: "+8809001122334",
        photo: "https://i.pravatar.cc/150?img=11",
        series: 15,
    },
    {
        name: "Laura Kim",
        email: "laura15@university.edu",
        currentJob: "Researcher at OPQ Labs",
        hometown: "Chittagong",
        phone: "+8809011223344",
        photo: "https://i.pravatar.cc/150?img=12",
        series: 15,
    },
    {
        name: "Michael Scott",
        email: "michael15@university.edu",
        currentJob: "Process Engineer at RST Corp",
        hometown: "Khulna",
        phone: "+8809122334455",
        photo: "https://i.pravatar.cc/150?img=13",
        series: 15,
    },
    {
        name: "Nina Patel",
        email: "nina15@university.edu",
        currentJob: "Quality Analyst at UVW Ltd",
        hometown: "Rajshahi",
        phone: "+8809233445566",
        photo: "https://i.pravatar.cc/150?img=14",
        series: 15,
    },
    {
        name: "Oliver King",
        email: "oliver15@university.edu",
        currentJob: "Lab Technician at XYZ Labs",
        hometown: "Sylhet",
        phone: "+8809344556677",
        photo: "https://i.pravatar.cc/150?img=15",
        series: 15,
    },
    {
        name: "Patricia Moore",
        email: "patricia15@university.edu",
        currentJob: "Process Engineer at ABC Corp",
        hometown: "Barisal",
        phone: "+8809455667788",
        photo: "https://i.pravatar.cc/150?img=16",
        series: 15,
    },
    {
        name: "Quentin Adams",
        email: "quentin15@university.edu",
        currentJob: "Chemical Analyst at DEF Inc",
        hometown: "Mymensingh",
        phone: "+8809566778899",
        photo: "https://i.pravatar.cc/150?img=17",
        series: 15,
    },
    {
        name: "Rachel Clark",
        email: "rachel15@university.edu",
        currentJob: "Project Engineer at GHI Ltd",
        hometown: "Tangail",
        phone: "+8809677889900",
        photo: "https://i.pravatar.cc/150?img=18",
        series: 15,
    },
    {
        name: "Samuel Turner",
        email: "samuel15@university.edu",
        currentJob: "Research Scientist at JKL Labs",
        hometown: "Jessore",
        phone: "+8809788990011",
        photo: "https://i.pravatar.cc/150?img=19",
        series: 15,
    },
    {
        name: "Tina Lopez",
        email: "tina15@university.edu",
        currentJob: "Process Engineer at MNO Corp",
        hometown: "Comilla",
        phone: "+8809899001122",
        photo: "https://i.pravatar.cc/150?img=20",
        series: 15,
    },

    {
        name: "Catherine Lee",
        email: "catherine16@university.edu",
        currentJob: "Chemical Analyst at DEF Inc",
        hometown: "Khulna",
        phone: "+8801122334455",
        photo: "https://i.pravatar.cc/150?img=3",
        series: 16,
    },
    {
        name: "David Kim",
        email: "david16@university.edu",
        currentJob: "Project Engineer at GHI Ltd",
        hometown: "Rajshahi",
        phone: "+8802233445566",
        photo: "https://i.pravatar.cc/150?img=4",
        series: 16,
    },
    {
        name: "Emily Davis",
        email: "emily17@university.edu",
        currentJob: "Production Manager at JKL Corp",
        hometown: "Sylhet",
        phone: "+8803344556677",
        photo: "https://i.pravatar.cc/150?img=5",
        series: 17,
    },
    {
        name: "Frank Brown",
        email: "frank17@university.edu",
        currentJob: "Quality Control Engineer at MNO Ltd",
        hometown: "Barisal",
        phone: "+8804455667788",
        photo: "https://i.pravatar.cc/150?img=6",
        series: 17,
    },
    {
        name: "George White",
        email: "george18@university.edu",
        currentJob: "Research Associate at PQR Labs",
        hometown: "Mymensingh",
        phone: "+8805566778899",
        photo: "https://i.pravatar.cc/150?img=7",
        series: 18,
    },
    {
        name: "Hannah Green",
        email: "hannah18@university.edu",
        currentJob: "Process Engineer at STU Corp",
        hometown: "Tangail",
        phone: "+8806677889900",
        photo: "https://i.pravatar.cc/150?img=8",
        series: 18,
    },
    {
        name: "Ian Black",
        email: "ian19@university.edu",
        currentJob: "Assistant Engineer at VWX Ltd",
        hometown: "Jessore",
        phone: "+8807788990011",
        photo: "https://i.pravatar.cc/150?img=9",
        series: 19,
    },
    {
        name: "Julia Brown",
        email: "julia19@university.edu",
        currentJob: "Lab Technician at YZA Labs",
        hometown: "Comilla",
        phone: "+8808899001122",
        photo: "https://i.pravatar.cc/150?img=10",
        series: 19,
    },
];

export const facultyData: { [key: string]: FacultyMember[] } = {
    "Department Head": [
        {
            name: "Dr. Alice Johnson",
            designation: "Department Head",
            email: "alice@university.edu",
            onLeave: false,
            photo: "https://i.pravatar.cc/150?img=1",
        },
    ],
    Professor: [
        {
            name: "Dr. Brian Smith",
            designation: "Professor",
            email: "brian@university.edu",
            onLeave: true,
            photo: "https://i.pravatar.cc/150?img=2",
        },
        {
            name: "Dr. Catherine Lee",
            designation: "Professor",
            email: "catherine@university.edu",
            onLeave: false,
            photo: "https://i.pravatar.cc/150?img=3",
        },
    ],
    "Associate Professor": [
        {
            name: "Dr. David Kim",
            designation: "Associate Professor",
            email: "david@university.edu",
            onLeave: false,
            photo: "https://i.pravatar.cc/150?img=4",
        },
    ],
    "Assistant Professor": [
        {
            name: "Dr. Emily Davis",
            designation: "Assistant Professor",
            email: "emily@university.edu",
            onLeave: true,
            photo: "https://i.pravatar.cc/150?img=5",
        },
        {
            name: "Dr. Frank Brown",
            designation: "Assistant Professor",
            email: "frank@university.edu",
            onLeave: false,
            photo: "https://i.pravatar.cc/150?img=6",
        },
    ],
    Lecturer: [
        {
            name: "Mr. George White",
            designation: "Lecturer",
            email: "george@university.edu",
            onLeave: false,
            photo: "https://i.pravatar.cc/150?img=7",
        },
        {
            name: "Ms. Hannah Green",
            designation: "Lecturer",
            email: "hannah@university.edu",
            onLeave: false,
            photo: "https://i.pravatar.cc/150?img=8",
        },
    ],
};
